### ISSUE TITLE
Linking error when run make 

### ISSUE THREAD

**Issue by ulquiorra-dev** [rw-r-r-0644/2048_WiiU#1]
Hi, I am trying to build this project but I am getting linking errors. I tried different configurations in my .bashrc but nothing so far. I am using this [https://github.com/yawut/sdl2-wiiu ](https://github.com/yawut/sdl2-wiiu ) version of the SDL2 wiiU port with I think the one used for this project. I am using Ubuntu 18.04. devkitpro, portlib and SDL2 installed. I hope someone can guide me.

**Here is my actual .bashrc**
```
export DEVKITPRO=/opt/devkitpro
export DEVKITPPC=$DEVKITPRO/devkitPPC
export PORTLIBS=$DEVKITPRO/portlibs/ppc

export PATH=$DEVKITPPC/bin:$DEVKITPRO/tools/bin:$PORTLIBS/include:$PATH
export PATH=$PORTLIBS/include/freetype2:$PATH
export PATH=$PORTLIBS/include/SDL2:$PATH
#export PATH=/opt/devkitpro/portlibs/wiiu/include/SDL2:$PATH

export WUT_ROOT=/opt/devkitpro/wut
export PATH=$WUT_ROOT/bin:$PATH
```

**Here the linking error we i run make**

> /opt/devkitpro/wut/share/wut.mk:14: "Using wut.mk is deprecated, and will be removed in a future release! Please switch to wut_rules as soon as possible - see https://github.com/devkitPro/wut/blob/master/samples/make/helloworld/Makefile for an example."
/opt/devkitpro/wut/share/wut.mk:91: "WUT_NEWLIB_LDFLAGS is deprecated and does nothing"
/opt/devkitpro/wut/share/wut.mk:91: "WUT_STDCPP_LDFLAGS is deprecated and does nothing"
/opt/devkitpro/wut/share/wut.mk:91: "WUT_DEVOPTAB_LDFLAGS is deprecated and does nothing"
LD 2048.rpx.elf
/bin/sh: 1: /opt/devkitpro/portlibs/wiiu/bin/powerpc-eabi-pkg-config: not found
/opt/devkitpro/devkitPPC/lib/gcc/powerpc-eabi/8.3.0/../../../../powerpc-eabi/bin/ld: source/Render.o: in function `Render::setDrawColor(int, int, int, int)':
Render.cpp:(.text+0x90): undefined reference to `SDL_SetRenderDrawColor'
/opt/devkitpro/devkitPPC/lib/gcc/powerpc-eabi/8.3.0/../../../../powerpc-eabi/bin/ld: source/Render.o: in function `Render::setDrawColor(SDL_Color const&)':
Render.cpp:(.text+0x100): undefined reference to `SDL_SetRenderDrawColor'
/opt/devkitpro/devkitPPC/lib/gcc/powerpc-eabi/8.3.0/../../../../powerpc-eabi/bin/ld: source/Render.o: in function `Render::clear()':
Render.cpp:(.text+0x144): undefined reference to `SDL_RenderClear'
/opt/devkitpro/devkitPPC/lib/gcc/powerpc-eabi/8.3.0/../../../../powerpc-eabi/bin/ld: source/Render.o: in function `Render::drawRect(int, int, int, int)':
Render.cpp:(.text+0x1c0): undefined reference to `SDL_RenderDrawRect'
/opt/devkitpro/devkitPPC/lib/gcc/powerpc-eabi/8.3.0/../../../../powerpc-eabi/bin/ld: source/Render.o: in function `Render::fillRect(int, int, int, int)':
Render.cpp:(.text+0x23c): undefined reference to `SDL_RenderFillRect'
/opt/devkitpro/devkitPPC/lib/gcc/powerpc-eabi/8.3.0/../../../../powerpc-eabi/bin/ld: source/Render.o: in function `Render::drawLine(int, int, int, int)':
Render.cpp:(.text+0x2a0): undefined reference to `SDL_RenderDrawLine'
/opt/devkitpro/devkitPPC/lib/gcc/powerpc-eabi/8.3.0/../../../../powerpc-eabi/bin/ld: source/Render.o: in function `Render::present()':
Render.cpp:(.text+0x2e4): undefined reference to `SDL_RenderPresent'
/opt/devkitpro/devkitPPC/lib/gcc/powerpc-eabi/8.3.0/../../../../powerpc-eabi/bin/ld: source/Render.o: in function `Render::createTexture(unsigned int, int, int, int)':
Render.cpp:(.text+0x348): undefined reference to `SDL_CreateTexture'
/opt/devkitpro/devkitPPC/lib/gcc/powerpc-eabi/8.3.0/../../../../powerpc-eabi/bin/ld: source/Render.o: in function `Render::createTextureFromSurface(SDL_Surface*)':
Render.cpp:(.text+0x398): undefined reference to `SDL_CreateTextureFromSurface'
/opt/devkitpro/devkitPPC/lib/gcc/powerpc-eabi/8.3.0/../../../../powerpc-eabi/bin/ld: source/Render.o: in function `Render::copy(SDL_Texture*, SDL_Rect const*, SDL_Rect const*)':
Render.cpp:(.text+0x3f8): undefined reference to `SDL_RenderCopy'
/opt/devkitpro/devkitPPC/lib/gcc/powerpc-eabi/8.3.0/../../../../powerpc-eabi/bin/ld: source/Render.o: in function `Render::setTarget(SDL_Texture*)':
Render.cpp:(.text+0x448): undefined reference to `SDL_SetRenderTarget'
/opt/devkitpro/devkitPPC/lib/gcc/powerpc-eabi/8.3.0/../../../../powerpc-eabi/bin/ld: source/Font.o: in function `Font::init(char const*, int)':
Font.cpp:(.text+0x30): undefined reference to `TTF_OpenFont'
/opt/devkitpro/devkitPPC/lib/gcc/powerpc-eabi/8.3.0/../../../../powerpc-eabi/bin/ld: Font.cpp:(.text+0x50): undefined reference to `SDL_GetError'
/opt/devkitpro/devkitPPC/lib/gcc/powerpc-eabi/8.3.0/../../../../powerpc-eabi/bin/ld: source/Font.o: in function `Font::free()':
Font.cpp:(.text+0xc0): undefined reference to `TTF_CloseFont'
/opt/devkitpro/devkitPPC/lib/gcc/powerpc-eabi/8.3.0/../../../../powerpc-eabi/bin/ld: source/Font.o: in function `Font::renderLatin(char const*, SDL_Color)':
Font.cpp:(.text+0x138): undefined reference to `TTF_RenderText_Blended'
/opt/devkitpro/devkitPPC/lib/gcc/powerpc-eabi/8.3.0/../../../../powerpc-eabi/bin/ld: source/Main.o: in function `main':
Main.cpp:(.text+0x3f0): undefined reference to `SDL_GetTicks'
/opt/devkitpro/devkitPPC/lib/gcc/powerpc-eabi/8.3.0/../../../../powerpc-eabi/bin/ld: Main.cpp:(.text+0x404): undefined reference to `SDL_PollEvent'
/opt/devkitpro/devkitPPC/lib/gcc/powerpc-eabi/8.3.0/../../../../powerpc-eabi/bin/ld: Main.cpp:(.text+0x4d4): undefined reference to `SDL_GetTicks'
/opt/devkitpro/devkitPPC/lib/gcc/powerpc-eabi/8.3.0/../../../../powerpc-eabi/bin/ld: source/Texture.o: in function `Texture::loadFromFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
Texture.cpp:(.text+0xc4): undefined reference to `IMG_Load'
/opt/devkitpro/devkitPPC/lib/gcc/powerpc-eabi/8.3.0/../../../../powerpc-eabi/bin/ld: Texture.cpp:(.text+0xe8): undefined reference to `SDL_GetError'
/opt/devkitpro/devkitPPC/lib/gcc/powerpc-eabi/8.3.0/../../../../powerpc-eabi/bin/ld: Texture.cpp:(.text+0x124): undefined reference to `SDL_MapRGB'
/opt/devkitpro/devkitPPC/lib/gcc/powerpc-eabi/8.3.0/../../../../powerpc-eabi/bin/ld: Texture.cpp:(.text+0x138): undefined reference to `SDL_SetColorKey'
/opt/devkitpro/devkitPPC/lib/gcc/powerpc-eabi/8.3.0/../../../../powerpc-eabi/bin/ld: Texture.cpp:(.text+0x16c): undefined reference to `SDL_GetError'
/opt/devkitpro/devkitPPC/lib/gcc/powerpc-eabi/8.3.0/../../../../powerpc-eabi/bin/ld: Texture.cpp:(.text+0x1b4): undefined reference to `SDL_FreeSurface'
/opt/devkitpro/devkitPPC/lib/gcc/powerpc-eabi/8.3.0/../../../../powerpc-eabi/bin/ld: source/Texture.o: in function `Texture::loadFromLatinText(Font*, char const*, SDL_Color)':
Texture.cpp:(.text+0x268): undefined reference to `SDL_GetError'
/opt/devkitpro/devkitPPC/lib/gcc/powerpc-eabi/8.3.0/../../../../powerpc-eabi/bin/ld: Texture.cpp:(.text+0x2ac): undefined reference to `SDL_GetError'
/opt/devkitpro/devkitPPC/lib/gcc/powerpc-eabi/8.3.0/../../../../powerpc-eabi/bin/ld: Texture.cpp:(.text+0x2f0): undefined reference to `SDL_FreeSurface'
/opt/devkitpro/devkitPPC/lib/gcc/powerpc-eabi/8.3.0/../../../../powerpc-eabi/bin/ld: source/Texture.o: in function `Texture::free()':
Texture.cpp:(.text+0x368): undefined reference to `SDL_DestroyTexture'
/opt/devkitpro/devkitPPC/lib/gcc/powerpc-eabi/8.3.0/../../../../powerpc-eabi/bin/ld: source/Texture.o: in function `Texture::setBlendMode(SDL_BlendMode)':
Texture.cpp:(.text+0x3d8): undefined reference to `SDL_SetTextureBlendMode'
/opt/devkitpro/devkitPPC/lib/gcc/powerpc-eabi/8.3.0/../../../../powerpc-eabi/bin/ld: source/Texture.o: in function `Texture::setAlpha(unsigned char)':
Texture.cpp:(.text+0x42c): undefined reference to `SDL_SetTextureAlphaMod'
/opt/devkitpro/devkitPPC/lib/gcc/powerpc-eabi/8.3.0/../../../../powerpc-eabi/bin/ld: source/Texture.o: in function `Texture::createBlank(int, int, SDL_TextureAccess)':
Texture.cpp:(.text+0x65c): undefined reference to `SDL_GetError'
/opt/devkitpro/devkitPPC/lib/gcc/powerpc-eabi/8.3.0/../../../../powerpc-eabi/bin/ld: source/SDLUtils.o: in function `InitSDL()':
SDLUtils.cpp:(.text+0x20): undefined reference to `SDL_Init'
/opt/devkitpro/devkitPPC/lib/gcc/powerpc-eabi/8.3.0/../../../../powerpc-eabi/bin/ld: SDLUtils.cpp:(.text+0x38): undefined reference to `SDL_GetError'
/opt/devkitpro/devkitPPC/lib/gcc/powerpc-eabi/8.3.0/../../../../powerpc-eabi/bin/ld: SDLUtils.cpp:(.text+0x70): undefined reference to `SDL_SetHint'
/opt/devkitpro/devkitPPC/lib/gcc/powerpc-eabi/8.3.0/../../../../powerpc-eabi/bin/ld: SDLUtils.cpp:(.text+0xb4): undefined reference to `SDL_CreateWindow'
/opt/devkitpro/devkitPPC/lib/gcc/powerpc-eabi/8.3.0/../../../../powerpc-eabi/bin/ld: SDLUtils.cpp:(.text+0xd4): undefined reference to `SDL_GetError'
/opt/devkitpro/devkitPPC/lib/gcc/powerpc-eabi/8.3.0/../../../../powerpc-eabi/bin/ld: SDLUtils.cpp:(.text+0x110): undefined reference to `SDL_CreateRenderer'
/opt/devkitpro/devkitPPC/lib/gcc/powerpc-eabi/8.3.0/../../../../powerpc-eabi/bin/ld: SDLUtils.cpp:(.text+0x130): undefined reference to `SDL_GetError'
/opt/devkitpro/devkitPPC/lib/gcc/powerpc-eabi/8.3.0/../../../../powerpc-eabi/bin/ld: SDLUtils.cpp:(.text+0x170): undefined reference to `IMG_Init'
/opt/devkitpro/devkitPPC/lib/gcc/powerpc-eabi/8.3.0/../../../../powerpc-eabi/bin/ld: SDLUtils.cpp:(.text+0x194): undefined reference to `SDL_GetError'
/opt/devkitpro/devkitPPC/lib/gcc/powerpc-eabi/8.3.0/../../../../powerpc-eabi/bin/ld: SDLUtils.cpp:(.text+0x1b8): undefined reference to `TTF_Init'
/opt/devkitpro/devkitPPC/lib/gcc/powerpc-eabi/8.3.0/../../../../powerpc-eabi/bin/ld: SDLUtils.cpp:(.text+0x1d8): undefined reference to `SDL_GetError'
/opt/devkitpro/devkitPPC/lib/gcc/powerpc-eabi/8.3.0/../../../../powerpc-eabi/bin/ld: SDLUtils.cpp:(.text+0x204): undefined reference to `SDL_NumJoysticks'
/opt/devkitpro/devkitPPC/lib/gcc/powerpc-eabi/8.3.0/../../../../powerpc-eabi/bin/ld: SDLUtils.cpp:(.text+0x234): undefined reference to `SDL_JoystickOpen'
/opt/devkitpro/devkitPPC/lib/gcc/powerpc-eabi/8.3.0/../../../../powerpc-eabi/bin/ld: source/SDLUtils.o: in function `CloseSDL()':
SDLUtils.cpp:(.text+0x2bc): undefined reference to `SDL_DestroyRenderer'
/opt/devkitpro/devkitPPC/lib/gcc/powerpc-eabi/8.3.0/../../../../powerpc-eabi/bin/ld: SDLUtils.cpp:(.text+0x2d8): undefined reference to `SDL_DestroyWindow'
/opt/devkitpro/devkitPPC/lib/gcc/powerpc-eabi/8.3.0/../../../../powerpc-eabi/bin/ld: SDLUtils.cpp:(.text+0x2e8): undefined reference to `TTF_Quit'
/opt/devkitpro/devkitPPC/lib/gcc/powerpc-eabi/8.3.0/../../../../powerpc-eabi/bin/ld: SDLUtils.cpp:(.text+0x2ec): undefined reference to `IMG_Quit'
/opt/devkitpro/devkitPPC/lib/gcc/powerpc-eabi/8.3.0/../../../../powerpc-eabi/bin/ld: SDLUtils.cpp:(.text+0x2f0): undefined reference to `SDL_Quit'

**Comment by rw-r-r-0644** [comment]
Hi!
Sorry for the absence of build instructions

To build this project you'll need to install the wiiu-pkg-config package, as it's used in the makefile to determine the correct libraries install path.
To install it, you can run `sudo dkp-pacman -S wiiu-pkg-config`

The sdl2 version at https://github.com/yawut/sdl2-wiiu is fairly old; you might want to use the wiiu version available at https://github.com/yawut/SDL instead, which adds support for hardware accelerated graphics and improves the audio driver (it's also a newer sdl library version).

Another library required for building is wiiu-libromfs, used for mounting the content of the romfs folder to romfs:/ inside the app.

A prebuilt version of wiiu-libromfs, along with the updated SDL and SDL libraries (SDL_gfx, SDL_mixer, ...) is available in the wiiu-fling repo (see https://gitlab.com/QuarkTheAwesome/wiiu-fling for instructions to add the repo to dkp-pacman).
After adding the repo, to install the required packages run:
`sudo dkp-pacman -Syu wiiu-libromfs wiiu-sdl2 wiiu-sdl2_gfx wiiu-sdl2_image wiiu-sdl2_mixer wiiu-sdl2_ttf`

Hope that helps!

PS: I just updated the Makefile for the latest wut/libromfs, make sure to pull the changes

**Comment by rw-r-r-0644** [comment]
(btw, I also just updated the Makefile for the newer wut/libromfs, make sure to pull the changes)

**Comment by ulquiorra-dev** [comment]
I just followed your instructions, made a pull.
It builds great, thanks a lot :D
